eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka

    ###因为该应用为注册中心
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true
server:
  port: 9000


spring:
  application:
    name: dong-zuul


zuul:
  routes:
    api-order:  # 路由名字，随意命名，配置网关
      path: /api-order/**
      serviceId: dong-order

    api-user:
      path: /api-user/**
      serviceId: dong-user

    dong-url:  #这个名字随便
      url: https://www.baidu.com
      path: /dong1/**


    dong2-url:
      serviceId: dong-user
      path: /dong2/**


    dong3-url:
      serviceId: xxx
      path: /dong3/**
#      #前缀访问
#  prefix: /dong
ribbon:
  eureka:
    enabled: false

dong-user:
  ribbon:
    listOfServers: https://www.baidu.com,https://www.bilibili.com/

